export const carouselSponsorData = [
    { src: "/partner/lineagas.png", alt: "Linea Gas gruppo Sapio", href: "https://www.lineagassrl.it/" },
    { src: "/partner/aquilastore.png", alt: "Aquila Store", href: "https://www.aquilastore.it/" },
    { src: "/partner/tmtrentino.png", alt: "TM Trentino", href: "https://www.instagram.com/tmtrentino/" },
    { src: "/partner/eldorado.png", alt: "Bar El Dorado", href: "https://www.instagram.com/bareldoradotrento/" },
    { src: "/partner/elitecleaning.png", alt: "Elite Cleaning", href: "https://www.elitecleaning.it/" },
    { src: "/partner/baritalia.png", alt: "Bar Italia", href: "https://www.facebook.com/CaffeVeneziaTrento/" },
    { src: "/partner/oenotrento.png", alt: "OenoTrento", href: "#" },
    { src: "/partner/sportking.png", alt: "Sport King", href: "https://www.kingsportwear.com/" },
    { src: "/partner/insiemed.png", alt: "Insiemed", href: "https://insiemed.it/" },
    { src: "/partner/fgtelecomunicazioni.png", alt: "FG Telecomunicazioni", href: "https://fgtelecom.it/" },
    { src: "/partner/twist.png", alt: "Twist", href: "https://twistpizza.it/" },
    { src: "/partner/iconwash.png", alt: "Icon Wash", href: "https://icon.tn.it/" },
    { src: "/partner/eurocardorigoni.png", alt: "Eurocar Dorigoni", href: "https://eurocar.it/it/trento" },
    { src: "/partner/sportrentino.png", alt: "SporTrentino.it", href: "https://www.sportrentino.it/" },
];